spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

server:
  # 下面是配置 undertow 作为服务器的参数
  undertow:
    # 以下的配置会影响 buffer，这些 buffer 会用于服务器连接的 IO 操作,有点类似 netty 的池化内存管理
    # 每块 buffer 的空间大小，越小的空间被利用越充分
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true
    threads:
      # 设置 IO 线程数，它主要执行非阻塞的任务，它们会负责多个连接，默认设置每个 CPU 核心一个线程
      io: 4
      # 阻塞任务线程池，当执行类似 servlet 请求阻塞操作，undertow 会从这个线程池中取得线程，它的值设置取决于系统的负载
      worker: 20