spring:
  config:
    import:
      - optional:cloud.yaml
      - optional:logging.yaml
  application:
    name: demo
  profiles:
    active: local
server:
  port: 10001
  forward-headers-strategy: framework