spring:
  config:
    import:
      - optional:api.yaml
      - optional:logging.yaml
  application:
    name: demo
  profiles:
    active: ${cloud.profiles.active:local}
server:
  port: 10001
  forward-headers-strategy: framework