server:
  port: 10001
  forward-headers-strategy: framework

spring:
  config:
    import:
      - optional:cloud.yaml
      - optional:doc.yml
      - optional:logging.yaml
      - optional:spring.yaml
  application:
    name: demo
  profiles:
    active: dev