spring:
  config:
    import:
      - optional:cloud.yaml
      - optional:logging.yaml
      - optional:file-server.yaml
  application:
    name: single
  profiles:
    active: dev
server:
  port: 9999
  forward-headers-strategy: framework