spring:
  data:
    redis:
      password: X4!A@iq#HM
      database: 0
      cluster:
        nodes:
          - 172.24.215.81:26379
          - 172.24.215.82:26379
          - 172.24.215.83:26379
  cloud:
    nacos:
      discovery:
        server-addr: 172.24.215.81:8848
        namespace: 1a2f3024-1c2f-4479-860b-f46acf08c597
        username: nacos
        password: zwcb3axb
logging:
  level:
    root: error