spring:
  data:
    redis:
      password: X4!A@iq#HM
      database: 0
      cluster:
        nodes:
          - 192.168.5.111:26445
          - 192.168.5.111:26446
          - 192.168.5.111:26447
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.111:4848
        namespace: 1a2f3024-1c2f-4479-860b-f46acf08c597
        username: nacos
        password: zwcb3axb