spring:
  data:
    redis:
      password: X1
      database: 0
      cluster:
        nodes:
          - 192.168.5.111:26445
          - 192.168.5.111:26446
          - 192.168.5.111:26447
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.111:4848
        namespace: 1a2f2024-1c23-4474-860b-f46ac108c597
        username: nacos
        password: zwc1