spring:
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 此处配置文件在各个应用中单独配置
      #    url: ''
      #    username: ''
      #    password: ''
      # 指定为 HikariDataSource
      type: com.zaxxer.hikari.HikariDataSource
      # hikari 连接池配置
      hikari:
        # 连接池名
        pool-name: HikariCP
        #最小空闲连接数
        minimum-idle: 5
        # 空闲连接存活最大时间，默认10分钟
        idle-timeout: 600000
        # 连接池最大连接数，默认是10
        maximum-pool-size: 10
        # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
        auto-commit: true
        # 此属性控制池中连接的最长生命周期，值 0 表示无限生命周期，默认 30 分钟
        max-lifetime: 1800000
        # 数据库连接超时时间,默认30秒
        connection-timeout: 30000
        # 连接测试query
        connection-test-query: SELECT 1

mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  check-config-location: true
  configuration:
    # Mybatis 二级缓存
    cache-enabled: false
    # 开启驼峰命名
    map-underscore-to-camel-case: true
    # 这个配置会将执行的 sql 打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
  global-config:
    #    db-config:
    # 主键类型
    #      id-type: assign_id
    # 展示 banner
    banner: false